---
- name: rebuild client module
  command: /etc/init.d/beegfs-client rebuild
  notify:
    - restart beegfs-client

- name: restart beegfs-client
  systemd:
    name: beegfs-client
    state: restarted
